2 - Calcular quantidade de números primos em um intervalo - Backend #2
AndresKindel/calculadora-primos pull request #14
Opened 2024-11-18 16:55 UTC by AndresKindel

closes #2

2024-12-06 13:33 UTC, wesleydecezere requested changes

2024-12-06 13:33 UTC, wesleydecezere commented on .idea/.gitignore
Essa `.idea/` precisa ser incluída no repositório? Parece coisa que o intellij consegue gerar sozinho

2024-12-06 13:33 UTC, wesleydecezere commented on backend/.gitignore
> +.idea
Inclusive aparece aqui, deve ter faltado inlcuir no `.gitigonre` do diretório raíz

2024-12-06 13:33 UTC, wesleydecezere commented on backend/mvnw.cmd
Mesma dúvida aqui, esses arquivos do maven wrapper precisar ser incluídos?

2024-12-06 13:33 UTC, wesleydecezere commented on backend/pom.xml
> +		</dependency>
Detalhe, mas poderia ficar junto com as outras do escopo de teste pra deixar mais organizado

2024-12-06 13:33 UTC, wesleydecezere commented on backend/pom.xml
> +	</scm>
Detalhe também, mas se não for preencher pode ser removido

2024-12-06 13:33 UTC, wesleydecezere commented on backend/src/main/kotlin/com/example/backend/resolver/MutationResolver.kt
> +        val tempoDeCalculo = endTime - startTime
```suggestion
        val result = measureTime { contarPrimos(input.number) } 
```
A medição do tempo poderia ser responsabilidade de uma outra função utilitária, que recebe a função a ter duração medida e retorna esse `Result`

Que tal?

2024-12-06 13:33 UTC, wesleydecezere commented on backend/src/main/kotlin/com/example/backend/resolver/MutationResolver.kt
> +data class Result(val numeroPrimos: Int, val tempoDeCalculo: Int)
Pelo padrão do PEC, esses DTOs estariam no package `resolver.model`

2024-12-06 13:33 UTC, wesleydecezere commented on backend/src/main/kotlin/com/example/backend/resolver/MutationResolver.kt
> +data class Result(val numeroPrimos: Int, val tempoDeCalculo: Int)
Os DTOs também poderiam receber nomes mais específicos, que deixessem mais clara a associação com o escopo ao qual pertencem

2024-12-06 13:33 UTC, wesleydecezere commented on backend/src/main/kotlin/com/example/backend/utils/CalculadoraPrimos.kt
> +    companion object {
```suggestion
object CalculadoraPrimos {
```
No Kotlin também existe o [`object`](https://kotlinlang.org/docs/object-declarations.html#object-declarations-overview), que pode ser utilizado quando todos os membros são estáticos

2024-12-06 13:33 UTC, wesleydecezere commented on backend/src/main/kotlin/com/example/backend/utils/CalculadoraPrimos.kt
> +            }
Podes usar o [`count`](https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.collections/count.html) pra deixar mais simples

2024-12-06 13:33 UTC, wesleydecezere commented on backend/src/test/kotlin/com/example/backend/resolver/MutationResolverTests.kt
> +        assertEquals(mockResult, result.numeroPrimos)
No PEC usamos a [`AssertJ`](https://assertj.github.io/doc/#assertj-core) para as verificações, esqueci de colocar na issue, mas acho que vale usar aqui também pra ir exercitando

2024-12-06 13:33 UTC, wesleydecezere commented on backend/src/test/kotlin/com/example/backend/resolver/MutationResolverTests.kt
Não faltou mockar o cálculo?

2024-12-06 13:33 UTC, wesleydecezere commented on backend/src/test/kotlin/com/example/backend/utils/CalculadoraPrimosTests.kt
Esse é um bom caso de uso do [teste parametrizado](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests) do JUnit

2024-12-06 13:33 UTC, wesleydecezere commented on backend/src/main/kotlin/com/example/backend/resolver/MutationResolver.kt
> +    fun processNumber(input: Input): Result {
Como essa operação não faz nenhuma alteração de dado no servidor, faria mais sentido ser uma query 

Esse [artigo](https://www.apollographql.com/blog/mutation-vs-query-when-to-use-graphql-mutation) explica bem a diferença entre as duas, a [doc](https://graphql.org/learn/mutations/) também pode ajudar

2024-12-09 17:07 UTC, AndresKindel commented on backend/src/test/kotlin/com/example/backend/resolver/MutationResolverTests.kt
tinha ficado de fazer isso mesmo

2025-01-15 14:46 UTC, wesleydecezere reviewed
🔝

2025-01-15 14:46 UTC, wesleydecezere commented on backend/pom.xml
> +		</dependency>
Não faltou o scope?

2025-01-15 14:46 UTC, wesleydecezere commented on backend/src/test/kotlin/com/example/backend/utils/CalculadoraPrimosTests.kt
> +        }
Com o [`@MethodSource`](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-MethodSource) ou o [`@FieldSource`](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-FieldSource) podes fornecer mais de um parâmetro pra cada iteração do teste

2025-01-15 14:46 UTC, wesleydecezere commented on backend/src/test/kotlin/com/example/backend/resolver/QueryResolverTests.kt
> +        assertThat(result.numeroPrimos).isEqualTo(mockResult)
Quando mockamos uma função, é interessante verificarmos que ela foi chamada com os argumentos corretos ([mockk](https://mockk.io/#:~:text=some%20coroutine%20code-,Validators,-Validator) / [mockito](https://site.mockito.org/javadoc/current/org/mockito/Mockito.html#1))

2025-01-15 14:46 UTC, wesleydecezere commented on backend/src/main/resources/graphql/schema.graphql
Sobre o uso de Long

* O PEC configura um custom scalar: [GraphQLScalarsConfiguration](https://github.com/laboratoriobridge/pec/blob/producao/backend/src/main/java/br/ufsc/bridge/pec/backend/app/config/graphql/types/GraphQLScalarsConfiguration.java)
* O Graphql-Java disponibiliza o pacote [extended-scalars](https://www.graphql-java.com/documentation/scalars/#:~:text=graphql%2Djava%2Dextended%2Dscalars), que facilita a configuração desse e vários outros tipos primitivos do Java

2025-01-15 14:46 UTC, wesleydecezere commented on backend/src/main/resources/graphql/schema.graphql
>  }
Pelo padrão do PEC, só definimos um objeto `input` quando a função recebe mais de um parâmetro, nesse caso poderia ser direto um `Int!` com nome significativo

2025-01-15 14:46 UTC, wesleydecezere commented on backend/src/main/resources/graphql/schema.graphql
> +    processarNumero(input: LimiteContagem): ResultadoContagem
A parâmetro e retorno são mesmo nullable?

2025-01-15 14:46 UTC, wesleydecezere commented on backend/src/main/resources/graphql/schema.graphql
>      tempoDeCalculo: Int
Pelo resolver parece que essas propriedades também não são nullable

2025-01-16 16:58 UTC, AndresKindel commented on backend/src/test/kotlin/com/example/backend/utils/CalculadoraPrimosTests.kt
> +        }
Boa, tinha esquecido disso

2025-01-21 20:13 UTC, wesleydecezere commented on backend/pom.xml
> +		</dependency>
Faltou aqui ou não precisou?

2025-01-23 22:49 UTC, wesleydecezere commented on backend/src/main/resources/graphql/schema.graphql
Foi feito no https://github.com/AndresKindel/calculadora-primos/pull/15

2025-01-23 22:55 UTC, wesleydecezere approved these changes

2025-01-23 22:55 UTC, wesleydecezere commented on backend/pom.xml
> +		</dependency>
Faltou aqui ou não foi necessário?

2025-01-23 22:55 UTC, wesleydecezere commented on backend/src/test/kotlin/com/example/backend/BackendApplicationTests.kt
Já que deve continuar vazio acho que pode excluir

2025-01-24 13:54 UTC, AndresKindel commented on backend/pom.xml
> +		</dependency>
coloquei la na https://github.com/AndresKindel/calculadora-primos/pull/15 tambem

2025-01-24 14:33 UTC, merged